### ISSUE TITLE
Updated feature flag not visible until page reload

### ISSUE THREAD

**Issue by edriste** [tryabby/abby#157]
Noticed a little bug today: 
When updating a feature flag value in the abby dashboard, it is not visible until the page is reloaded.

**Steps to reproduce:**

1. Open a feature flag configuration on abby
2. Change the value of the feature flag
3. Press the "Update flag" button

**Expected behaviour:**

The new value is visible on the dashboard

**Current behaviour:**

The dashboard stays the same way as before until the page is manually reloaded

**Comment by cstrnt** [comment]
@edriste should be fixed now :)
