### ISSUE TITLE
Express Integration

### ISSUE THREAD

**Issue by cstrnt** [tryabby/abby#69]
Description:
Abby should have an integration for Express. This Integration should behave pretty closely to the existing Integrations and have feature parity.

Acceptance Criteria:
- Must be inside of packages/express
- Must be named @tryabby/express
- Needs to consume @tryabby/core internally
- Must be written in Typescript and have the same type quality as React etc.
- needs to have the following functionality
  - expose a middleware function which has some internal cache for the Abby API call  
  - a function which returns the user's currently selected variant as well as the onAct method
  - a function which returns the value of the given feature flag
  - a function which returns the value of the given feature flag
- there should be tests for the types and the code

**Comment by lazyMonk1010** [comment]
i want to work on this issue , please assign me this issue

**Comment by cstrnt** [comment]
@lazyMonk1010  Done :)

**Comment by cstrnt** [comment]
@lazyMonk1010 do you need any assistance here?

**Comment by thawankeane** [comment]
@cstrnt a little bit off topic but, does Abby have any plans to add integration for Nest.js? I think that the API would be similar to `@tryabby/angular`

**Comment by cstrnt** [comment]
@thawankeane Oh defo! The more the merrier! If you like feel free to join our [discord](https://discord.gg/XaTJ76J3m3) or let us know some of your needs :)

**Comment by cstrnt** [comment]
@thawankeane currently on it!
