### ISSUE TITLE
Update the `manage` Button in project Settings

### ISSUE THREAD

**Issue by cstrnt** [tryabby/abby#71]
The `Manage` Button in the Project Settings has a different style than the other buttons. This should not be the case

![Screenshot 2023-10-02 at 15 25 10](https://github.com/tryabby/abby/assets/20679094/d3718034-a975-4eeb-8197-35877a1b3599)

**Comment by Franqsanz** [comment]
Hello, in which file is it located?

**Comment by CakeWithDivinity** [comment]
It would make sense to search through the whole application for those "unstyled" buttons. There are a few in the signup process too 
![image](https://github.com/tryabby/abby/assets/29003122/feb272a6-0494-4a38-92c0-00bfe556b1b5)

**Comment by cstrnt** [comment]
@Franqsanz do you need any assistance here? :)
