### ISSUE TITLE
Add a nicer WYSIWYG Editor for the Feature Flag / Remote Config Description

### ISSUE THREAD

**Issue by cstrnt** [tryabby/abby#72]
The current editor is really basic and doesn't really look nice. Also it doesn't have any buttons for formatting

![Screenshot 2023-10-02 at 15 26 22](https://github.com/tryabby/abby/assets/20679094/5fb9f8c3-948a-4eb8-a397-1cc2c4f261fe)

**Comment by shahank42** [comment]
Hey @cstrnt have you heard of Milkdown?
https://milkdown.dev/

Maybe it could be integrated here

**Comment by cstrnt** [comment]
Hey @shahank42 I think tiptap is already pretty good. I think we just need a nicer GUI for the user :)
