### ISSUE TITLE
Improve Remote Config Type UI when updating Remote Config Value

### ISSUE THREAD

**Issue by cstrnt** [tryabby/abby#73]
The disabled state for the _Update Remote Config Modal_ looks odd. There should be more visual clarity that the fields are disabled and a better indicator for the current value

![Screenshot 2023-10-02 at 15 28 14](https://github.com/tryabby/abby/assets/20679094/d3f2d64d-7103-4612-a287-bf90e690f21f)

**Comment by imSyntn** [comment]
can you explain the issue a little bit clearly

**Comment by arjun-gr** [comment]
Okay so if i am correct, You want the selected option to be more visible than the other 2 which are disabled ?

**Comment by CakeWithDivinity** [comment]
@arjun-gr Yeah, essentially the whole field is disabled, so it should not seem clickable, but it should be clear to the user what option is selected.

**Comment by deverestHood** [comment]
Hello! Could you assign this issue to me, and point me towards the files/code for the remote config type UI? Thanks so much!
