### ISSUE TITLE
Improve Onboarding Process

### ISSUE THREAD

**Issue by cstrnt** [tryabby/abby#79]
**Problem:**
Right now the onboarding process is cumbersome and can easily be skipped. 

**Acceptance Criteria:**

- The Selects for the experience in Feature Flags / A/B testing should be a horizontal radio group (use https://ui.shadcn.com/docs/components/radio-group)
- The continue button should be disabled until the user has made a decision on **all** steps

**Comment by zaCKoZAck0** [comment]
Please assign it to me, I want to work on it.

**Comment by zaCKoZAck0** [comment]
Sorry for this but I couldn't find where to make changes, can you please share a screenshot or a reference here please.

**Comment by cstrnt** [comment]
@zaCKoZAck0 All of this is in the `apps/web/src/pages/welcome.tsx` file

**Comment by cstrnt** [comment]
Thanks @zaCKoZAck0, this is merged #82
