### ISSUE TITLE
@tryabby/svelte 2.0.1 package broken

### ISSUE THREAD

**Issue by shiftgeist** [tryabby/abby#92]
The package only contains `README.md` and `package.json`

<img width="827" alt="image" src="https://github.com/tryabby/abby/assets/30648730/69b18435-4af5-4c06-8270-d1f929ca2c2d">

> Image source: https://www.npmjs.com/package/@tryabby/svelte?activeTab=code

## Steps to reproduce:

1. `pnpm i @tryabby/svelte`
2. ```shell
   ❯ ls -la node_modules/@tryabby/svelte
   .rw-r--r-- 1.8k felix 28 Oct 21:12 package.json
   .rw-r--r-- 5.8k felix 28 Oct 21:12 README.md
   ```

**Comment by cstrnt** [comment]
Should be fixed now :)

**Comment by shiftgeist** [comment]
Thanks
